# netlify.toml
[build]
  publish = "dist"        # atau sesuai output build kamu
  command = "npm run build"

[[redirects]]
  from     = "/api"
  to       = "https://script.google.com/macros/s/AKfyYOUR_WEBAPP_ID/exec"
  status   = 200
  force    = true
  methods  = ["GET", "POST", "OPTIONS"]
